# Generated by Django 4.2.7 on 2023-11-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageTileItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_title_up', models.CharField(max_length=50)),
                ('adv_main', models.CharField(max_length=4)),
                ('adv_title_down', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NavItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=30)),
                ('nav_link', models.CharField(max_length=50)),
                ('nav_id', models.PositiveIntegerField()),
            ],
        ),
    ]
